[workspace]
resolver = "2"
members = [
  "native_port",
  "discovery",
  "filesystem",
  "identity",
  "task_composer",
]

[workspace.dependencies]
compio = { version = "0.16.0", features = [
  "dispatcher",
  "macros",
  "nightly",
  "process",
  "time",
] }
flume = { version = "0.11.1", default-features = false, features = ["async"] }
futures-util = "0.3.31"
thiserror = "2.0.17"
typed-builder = "0.23.0"
mime = "0.3.17"
camino = "1.2.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
tracing-panic = "0.1"
see = { git = "https://github.com/OpenTritium/see.git", branch = "into_stream", features = [
  "stream",
] }
async-broadcast = "0.7.2"
url = { version = "2.5.7", features = ["serde"] }
async-lock = "3.4.1"
