[package]
name = "falcon_config"
version = "0.1.0"
edition = "2024"

[dependencies]
confy = "2.0.0"
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
tempfile = { workspace = true }
toml = "0.9"
