[package]
name = "native_port"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"
compio = { workspace = true }
identity = { path = "../identity" }
see = { workspace = true }
task_composer = { path = "../task_composer" }
