[package]
name = "falcon_discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { version = "6.1.0", features = ["inline"] }
hostname = "0.4.1"
mdns-sd = "0.17.0"
network-interface = "2.0.3"
compio = { workspace = true }
futures-util = { workspace = true }
